### ISSUE TITLE
Conda install fails when installed with Pytorch

### ISSUE THREAD

**Issue by FuriouslyCurious** [mne-tools/mne-nirs#423] opened 2021-12-30 03:50 UTC
### Issue

When I try to install pytorch, sci-kit family of packages, and mne-nirs at the same time, conda solver is not able to work through all the dependencies and gets stuck in a recursive solver loop with following error message:

```
#8 21.50 Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
#8 50.51 Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
#8 86.88 Collecting package metadata (repodata.json): ...working... done
#8 154.0 Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Examining scikit-image:  18%|█▊        | 10/56 [00:20<02:03,  2.69s/it]
```

### Potential Resolution

Potential resolution would be to revise requirements.txt / .yml  to be less restrictive.  This would allow conda solver to find a solution.  I am submitting a proposed pull request that fixes conda package names.

### Temporary Workaround

Install MNE and MNE-NIRS with pip instead of conda

**Comment by drammock** [comment] 2021-12-30 15:50
closing as duplicate of https://github.com/mne-tools/mne-python/issues/10165

**Closed by drammock** 2021-12-30 15:50 UTC
